In [38]:
import pandas as pd
import numpy as np
from pathlib import Path

DATA_PATH = Path('data')
KEY_ROWS = ['alabama'
            ,'alaska'
            ,'arizona'
            ,'arkansas'
            ,'california'
            ,'colorado'
            ,'connecticut'
            ,'delaware'
            ,'florida'
            ,'georgia'
            ,'hawaii'
            ,'idaho'
            ,'illinois'
            ,'indiana'
            ,'iowa'
            ,'kansas'
            ,'kentucky'
            ,'louisiana'
            ,'maine'
            ,'maryland'
            ,'massachusetts'
            ,'michigan'
            ,'minnesota'
            ,'mississippi'
            ,'missouri'
            ,'montana'
            ,'nebraska'
            ,'nevada'
            ,'new_hampshire'
            ,'new_jersey'
            ,'new_mexico'
            ,'new_york'
            ,'north_carolina'
            ,'north_dakota'
            ,'ohio'
            ,'oklahoma'
            ,'oregon'
            ,'pennsylvania'
            ,'rhode_island'
            ,'south_carolina'
            ,'south_dakota'
            ,'tennessee'
            ,'texas'
            ,'utah'
            ,'vermont'
            ,'virginia'
            ,'washington'
            ,'west_virginia'
            ,'wisconsin'
            ,'wyoming'
            ,'washington_dc'
            ,'puerto_rico']

In [39]:
census_population_df = pd.read_csv(DATA_PATH / 'CENSUS_POPULATION_STATE.tsv', sep='\t')
census_population_df.head()

,Label (Grouping),Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,Arizona!!Estimate,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
0,SEX AND AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total population,"5,108,468",*****,"5,108,468",(X),"733,406",*****,"733,406",(X),"7,431,344",...,"5,910,955",(X),"584,057",*****,"584,057",(X),"3,205,691",*****,"3,205,691",(X)
2,Male,"2,471,801","±5,359",48.40%,±0.1,"385,855","±2,547",52.60%,±0.3,"3,708,672",...,50.10%,±0.1,"295,735","±2,677",50.60%,±0.5,"1,518,924","±4,095",47.40%,±0.1
3,Female,"2,636,667","±5,359",51.60%,±0.1,"347,551","±2,547",47.40%,±0.3,"3,722,672",...,49.90%,±0.1,"288,322","±2,677",49.40%,±0.5,"1,686,767","±4,095",52.60%,±0.1
4,Sex ratio (males per 100 females),93.7,±0.4,(X),(X),111,±1.5,(X),(X),99.6,...,(X),(X),102.6,±1.9,(X),(X),90,±0.5,(X),(X)

In [40]:
census_mhi_df = pd.read_csv(DATA_PATH / 'CENSUS_MHI_STATE.csv')
census_mhi_df.head()

,Label (Grouping),Alabama!!Number!!Estimate,Alabama!!Number!!Margin of Error,Alabama!!Percent Distribution!!Estimate,Alabama!!Percent Distribution!!Margin of Error,Alabama!!Median income (dollars)!!Estimate,Alabama!!Median income (dollars)!!Margin of Error,Alaska!!Number!!Estimate,Alaska!!Number!!Margin of Error,Alaska!!Percent Distribution!!Estimate,...,Wyoming!!Percent Distribution!!Estimate,Wyoming!!Percent Distribution!!Margin of Error,Wyoming!!Median income (dollars)!!Estimate,Wyoming!!Median income (dollars)!!Margin of Error,Puerto Rico!!Number!!Estimate,Puerto Rico!!Number!!Margin of Error,Puerto Rico!!Percent Distribution!!Estimate,Puerto Rico!!Percent Distribution!!Margin of Error,Puerto Rico!!Median income (dollars)!!Estimate,Puerto Rico!!Median income (dollars)!!Margin of Error
0,HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Households,"1,969,105","±6,574","1,969,105","±6,574","62,027",±400,"267,865","±1,441","267,865",...,"238,176","±1,220","74,815","±1,225","1,239,243","±5,156","1,239,243","±5,156","25,096",±232
2,One race--,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,White,"1,327,559","±5,320",67.40%,±0.2,"71,604",±507,"185,313","±1,530",69.20%,...,89.60%,±0.3,"75,867","±1,139","425,472","±4,598",34.30%,±0.3,"25,679",±382
4,Black or African American,"513,880","±3,525",26.10%,±0.2,"42,373",±666,"8,124",±573,3.00%,...,0.70%,±0.1,"40,750","±17,900","94,224","±2,079",7.60%,±0.2,"24,576",±761

In [41]:
regions_key_df = pd.read_csv(DATA_PATH / 'KEYS.csv')
regions_key_df.head()

,key_row,realtor_cbsa_title,zillow_region_name,redfin_region,census_msa,region_type,state_abbreviation,alternative_name
0,united_states,United States,United States,National,United States,country,US,United States
1,alabama,alabama,Alabama,Alabama,Alabama,state,AL,Alabama
2,alaska,alaska,Alaska,Alaska,Alaska,state,AK,Alaska
3,arizona,arizona,Arizona,Arizona,Arizona,state,AZ,Arizona
4,arkansas,arkansas,Arkansas,Arkansas,Arkansas,state,AR,Arkansas

In [42]:
redfin_median_sale_price_df = pd.read_csv(DATA_PATH / 'REDFIN_MEDIAN_SALE_PRICE.csv', index_col=0, skiprows=1)
redfin_median_sale_price_df.head()

,January 2012,February 2012,March 2012,April 2012,May 2012,June 2012,July 2012,August 2012,September 2012,October 2012,...,May 2024,June 2024,July 2024,August 2024,September 2024,October 2024,November 2024,December 2024,January 2025,February 2025
Region,,,,,,,,,,,,,,,,,,,,,
Alabama,$131K,$153K,$140K,$142K,$155K,$164K,$154K,$158K,$145K,$150K,...,$288K,$293K,$286K,$280K,$281K,$275K,$279K,$280K,$276K,$283K
Alaska,$240K,$246K,$243K,$242K,$251K,$260K,$254K,$258K,$259K,$259K,...,$391K,$395K,$388K,$398K,$388K,$387K,$387K,$384K,$387K,$385K
Arizona,$125K,$127K,$135K,$142K,$149K,$151K,$150K,$153K,$154K,$156K,...,$450K,$450K,$443K,$441K,$441K,$445K,$446K,$449K,$453K,$456K
Arkansas,$100K,$108K,$127K,$120K,$123K,$121K,$115K,$125K,$137K,$122K,...,$263K,$267K,$256K,$264K,$256K,$258K,$259K,$256K,$255K,$255K
California,$281K,$286K,$306K,$321K,$329K,$340K,$345K,$343K,$347K,$351K,...,$859K,$857K,$837K,$817K,$815K,$839K,$830K,$802K,$785K,$833K

In [43]:
def get_regions_mapping(
        regions: pd.Series,
        regions_key: pd.DataFrame,
) -> pd.Series:
    key_row_mapper = regions_key[['key_row', 'zillow_region_name']]
    key_row_mapper.drop_duplicates(['key_row'], keep='first', inplace=True)
    key_row_mapper = key_row_mapper.set_index('key_row')
    key_row_mapper = key_row_mapper.to_dict()['zillow_region_name']
    # mapped_state_names = output_df['key_row'].map(key_row_mapper)
    mapped_regions = regions.map(key_row_mapper)
    return mapped_regions

def get_census_population(
        census_population: pd.DataFrame,
        mapped_regions: pd.Series
) -> np.ndarray:
    # Getting all regions population data
    full_population_series = census_population[census_population.iloc[:, 0] == "    Total population"].iloc[0]
    
    region_col_names = mapped_regions + "!!Estimate"
    regions_population = full_population_series[region_col_names].values
    return regions_population

def get_median_household_income(
        census_mhi: pd.DataFrame,
        mapped_regions: pd.Series
) -> np.ndarray:
    full_series = census_mhi[census_mhi.iloc[:, 0] == "    Households"].iloc[0]
    
    region_col_names = mapped_regions + "!!Median income (dollars)!!Estimate"
    return full_series[region_col_names].values

# Function to convert number to ordinal
def ordinal(n):
    if 10 <= n % 100 <= 20:
        suffix = 'th'
    else:
        suffix = {1: 'st', 2: 'nd', 3: 'rd'}.get(n % 10, 'th')
    return f"{n}{suffix}"

def get_rank(
        numbers_series: pd.Series
) -> pd.Series:
    numbers_series = numbers_series.copy()
    # clean str column and convert to number datatype if it is not numeric
    if not pd.api.types.is_numeric_dtype(numbers_series):
        numbers_series = pd.to_numeric(numbers_series.str.replace(r'[^0-9.]', ''))   # clean symbols like `$`, `,` and convert to numeric 
    rankings = numbers_series.rank(ascending=False, method='min').astype(int)
    rankings_with_suffix = rankings.apply(ordinal)
    return rankings_with_suffix

def generate_blurb(
        df: pd.DataFrame,
        blurb_template: str,
        **columns
):
    """
    Generates a blurb using any number of columns mapped to template placeholders.

    Parameters:
    - df: pandas DataFrame
    - template: string with named placeholders (e.g. "{city} is {rank}")
    - **columns: mapping of template placeholders to DataFrame column names

    Returns:
    - pandas Series of generated blurbs
    """
    return df.apply(lambda row: blurb_template.format(**{k: row[v] for k, v in columns.items()}), axis=1)

output_df = pd.DataFrame()
output_df['key_row'] = KEY_ROWS
output_df['mapped_key_row'] = get_regions_mapping(regions=output_df['key_row'], regions_key=regions_key_df)

output_df['census_population'] = get_census_population(census_population=census_population_df, mapped_regions=output_df['mapped_key_row'])
output_df['population_rank'] = get_rank(output_df['census_population'])
output_df['population_blurb'] = generate_blurb(
    df=output_df,
    blurb_template="{region} is {rank} in the nation in population among states, DC, and Puerto Rico.",
    region="mapped_key_row", rank='population_rank'
)

output_df['median_household_income'] = get_median_household_income(census_mhi=census_mhi_df, mapped_regions=output_df['mapped_key_row'])
output_df['median_household_income_rank'] = get_rank(output_df['median_household_income'])
output_df['median_household_income_blurb'] = generate_blurb(
    df=output_df,
    blurb_template="{region} is {rank} in the nation in median household income among states, DC, and Puerto Rico.",
    region="mapped_key_row", rank='population_rank'
)

currency_cols = ['median_household_income', 'median_sale_price']
output_df

e:\git\DA_TASK_2025-04-27\venv\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,key_row,mapped_key_row,census_population,population_rank,population_blurb,median_household_income,median_household_income_rank,median_household_income_blurb
0,alabama,Alabama,"5,108,468",24th,Alabama is 24th in the nation in population am...,"62,027",47th,Alabama is 24th in the nation in median househ...
1,alaska,Alaska,"733,406",49th,Alaska is 49th in the nation in population amo...,"89,336",13th,Alaska is 49th in the nation in median househo...
2,arizona,Arizona,"7,431,344",14th,Arizona is 14th in the nation in population am...,"76,872",21st,Arizona is 14th in the nation in median househ...
3,arkansas,Arkansas,"3,067,732",34th,Arkansas is 34th in the nation in population a...,"58,773",49th,Arkansas is 34th in the nation in median house...
4,california,California,"38,965,193",1st,California is 1st in the nation in population ...,"96,334",6th,California is 1st in the nation in median hous...
5,colorado,Colorado,"5,877,610",21st,Colorado is 21st in the nation in population a...,"92,470",10th,Colorado is 21st in the nation in median house...
6,connecticut,Connecticut,"3,617,176",29th,Connecticut is 29th in the nation in populatio...,"93,760",9th,Connecticut is 29th in the nation in median ho...
7,delaware,Delaware,"1,031,890",46th,Delaware is 46th in the nation in population a...,"82,855",17th,Delaware is 46th in the nation in median house...
8,florida,Florida,"22,610,726",3rd,Florida is 3rd in the nation in population amo...,"71,711",35th,Florida is 3rd in the nation in median househo...
9,georgia,Georgia,"11,029,227",8th,Georgia is 8th in the nation in population amo...,"74,664",29th,Georgia is 8th in the nation in median househo...
10,hawaii,Hawaii,"1,435,138",41st,Hawaii is 41st in the nation in population amo...,"98,317",5th,Hawaii is 41st in the nation in median househo...
11,idaho,Idaho,"1,964,726",39th,Idaho is 39th in the nation in population amon...,"74,636",30th,Idaho is 39th in the nation in median househol...
12,illinois,Illinois,"12,549,689",6th,Illinois is 6th in the nation in population am...,"81,702",18th,Illinois is 6th in the nation in median househ...
13,indiana,Indiana,"6,862,199",17th,Indiana is 17th in the nation in population am...,"70,051",37th,Indiana is 17th in the nation in median househ...
14,iowa,Iowa,"3,207,004",31st,Iowa is 31st in the nation in population among...,"73,147",31st,Iowa is 31st in the nation in median household...
15,kansas,Kansas,"2,940,547",35th,Kansas is 35th in the nation in population amo...,"72,639",32nd,Kansas is 35th in the nation in median househo...
16,kentucky,Kentucky,"4,526,154",26th,Kentucky is 26th in the nation in population a...,"62,417",45th,Kentucky is 26th in the nation in median house...
17,louisiana,Louisiana,"4,573,749",25th,Louisiana is 25th in the nation in population ...,"60,023",48th,Louisiana is 25th in the nation in median hous...
18,maine,Maine,"1,395,722",43rd,Maine is 43rd in the nation in population amon...,"71,773",34th,Maine is 43rd in the nation in median househol...
19,maryland,Maryland,"6,180,253",19th,Maryland is 19th in the nation in population a...,"101,652",2nd,Maryland is 19th in the nation in median house...
20,massachusetts,Massachusetts,"7,001,399",16th,Massachusetts is 16th in the nation in populat...,"101,341",3rd,Massachusetts is 16th in the nation in median ...
21,michigan,Michigan,"10,037,261",10th,Michigan is 10th in the nation in population a...,"71,149",36th,Michigan is 10th in the nation in median house...
22,minnesota,Minnesota,"5,737,915",22nd,Minnesota is 22nd in the nation in population ...,"87,556",14th,Minnesota is 22nd in the nation in median hous...
23,mississippi,Mississippi,"2,939,690",36th,Mississippi is 36th in the nation in populatio...,"54,915",51st,Mississippi is 36th in the nation in median ho...
24,missouri,Missouri,"6,196,156",18th,Missouri is 18th in the nation in population a...,"68,920",41st,Missouri is 18th in the nation in median house...
25,montana,Montana,"1,132,812",44th,Montana is 44th in the nation in population am...,"69,922",38th,Montana is 44th in the nation in median househ...
26,nebraska,Nebraska,"1,978,379",38th,Nebraska is 38th in the nation in population a...,"74,985",27th,Nebraska is 38th in the nation in median house...
27,nevada,Nevada,"3,194,176",33rd,Nevada is 33rd in the nation in population amo...,"75,561",26th,Nevada is 33rd in the nation in median househo...
28,new_hampshire,New Hampshire,"1,402,054",42nd,New Hampshire is 42nd in the nation in populat...,"95,628",7th,New Hampshire is 42nd in the nation in median ...
29,new_jersey,New Jersey,"9,290,841",11th,New Jersey is 11th in the nation in population...,"101,050",4th,New Jersey is 11th in the nation in median hou...
30,new_mexico,New Mexico,"2,114,371",37th,New Mexico is 37th in the nation in population...,"62,125",46th,New Mexico is 37th in the nation in median hou...
31,new_york,New York,"19,571,216",4th,New York is 4th in the nation in population am...,"84,578",16th,New York is 4th in the nation in median househ...
32,north_carolina,North Carolina,"10,835,491",9th,North Carolina is 9th in the nation in populat...,"69,904",39th,North Carolina is 9th in the nation in median ...
33,north_dakota,North Dakota,"783,926",48th,North Dakota is 48th in the nation in populati...,"75,949",24th,North Dakota is 48th in the nation in median h...
34,ohio,Ohio,"11,785,935",7th,Ohio is 7th in the nation in population among ...,"69,680",40th,Ohio is 7th in the nation in median household ...
35,oklahoma,Oklahoma,"4,053,824",28th,Oklahoma is 28th in the nation in population a...,"63,603",44th,Oklahoma is 28th in the nation in median house...
36,oregon,Oregon,"4,233,358",27th,Oregon is 27th in the nation in population amo...,"80,426",19th,Oregon is 27th in the nation in median househo...
37,pennsylvania,Pennsylvania,"12,961,683",5th,Pennsylvania is 5th in the nation in populatio...,"76,081",23rd,Pennsylvania is 5th in the nation in median ho...
38,rhode_island,Rhode Island,"1,095,962",45th,Rhode Island is 45th in the nation in populati...,"86,372",15th,Rhode Island is 45th in the nation in median h...
39,south_carolina,South Carolina,"5,373,555",23rd,South Carolina is 23rd in the nation in popula...,"66,818",43rd,South Carolina is 23rd in the nation in median...
40,south_dakota,South Dakota,"919,318",47th,South Dakota is 47th in the nation in populati...,"72,421",33rd,South Dakota is 47th in the nation in median h...
41,tennessee,Tennessee,"7,126,489",15th,Tennessee is 15th in the nation in population ...,"67,097",42nd,Tennessee is 15th in the nation in median hous...
42,texas,Texas,"30,503,301",2nd,Texas is 2nd in the nation in population among...,"76,292",22nd,Texas is 2nd in the nation in median household...
43,utah,Utah,"3,417,734",30th,Utah is 30th in the nation in population among...,"91,750",11th,Utah is 30th in the nation in median household...
44,vermont,Vermont,"647,464",51st,Vermont is 51st in the nation in population am...,"78,024",20th,Vermont is 51st in the nation in median househ...
45,virginia,Virginia,"8,715,698",12th,Virginia is 12th in the nation in population a...,"90,974",12th,Virginia is 12th in the nation in median house...
46,washington,Washington,"7,812,880",13th,Washington is 13th in the nation in population...,"94,952",8th,Washington is 13th in the nation in median hou...
47,west_virginia,West Virginia,"1,770,071",40th,West Virginia is 40th in the nation in populat...,"57,917",50th,West Virginia is 40th in the nation in median ...
48,wisconsin,Wisconsin,"5,910,955",20th,Wisconsin is 20th in the nation in population ...,"75,670",25th,Wisconsin is 20th in the nation in median hous...
49,wyoming,Wyoming,"584,057",52nd,Wyoming is 52nd in the nation in population am...,"74,815",28th,Wyoming is 52nd in the nation in median househ...
50,washington_dc,District of Columbia,"678,972",50th,District of Columbia is 50th in the nation in ...,"106,287",1st,District of Columbia is 50th in the nation in ...
51,puerto_rico,Puerto Rico,"3,205,691",32nd,Puerto Rico is 32nd in the nation in populatio...,"25,096",52nd,Puerto Rico is 32nd in the nation in median ho...